/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * SavidhanSamraksha MPLADS monitoring and risk intelligence API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import { customFetch } from './custom-fetch';
const withQueryKey = (query, queryKey) => {
    const result = { queryKey };
    for (const key of Object.keys(query)) {
        // The explicit queryKey always wins, matching the previous
        // `{ ...query, queryKey }` spread where it was set last.
        if (key === 'queryKey')
            continue;
        Object.defineProperty(result, key, {
            enumerable: true,
            configurable: true,
            get: () => query[key],
        });
    }
    return result;
};
export const getHealthCheckUrl = () => {
    return `/api/healthz`;
};
/**
 * @summary Health check
 */
export const healthCheck = async (options) => {
    return customFetch(getHealthCheckUrl(), {
        ...options,
        method: 'GET'
    });
};
export const getHealthCheckQueryKey = () => {
    return [
        `/api/healthz`
    ];
};
export const getHealthCheckQueryOptions = (options) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};
    const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();
    const queryFn = ({ signal }) => healthCheck({ signal, ...requestOptions });
    return { queryKey, queryFn, ...queryOptions };
};
/**
 * @summary Health check
 */
export function useHealthCheck(options) {
    const queryOptions = getHealthCheckQueryOptions(options);
    const query = useQuery(queryOptions);
    return withQueryKey(query, queryOptions.queryKey);
}
export const getLoginUrl = () => {
    return `/api/auth/login`;
};
/**
 * @summary Authenticate a synthetic authority user
 */
export const login = async (loginInput, options) => {
    const getHeaders = (h) => {
        if (!h)
            return {};
        if (h instanceof Headers)
            return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(Array.from(h, (entry) => Array.from(entry)));
        }
        const headers = {};
        for (const [name, value] of Object.entries(h)) {
            if (value !== undefined)
                headers[name] = value;
        }
        return headers;
    };
    return customFetch(getLoginUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
        body: JSON.stringify(loginInput)
    });
};
export const getLoginMutationKey = () => ['login'];
export const getLoginMutationOptions = (options) => {
    const mutationKey = getLoginMutationKey();
    const { mutation: mutationOptions, request: requestOptions } = options ?
        options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
            options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey, }, request: undefined };
    const mutationFn = (props) => {
        const { data } = props ?? {};
        return login(data, requestOptions);
    };
    return { mutationFn, ...mutationOptions };
};
/**
* @summary Authenticate a synthetic authority user
*/
export const useLogin = (options) => {
    return useMutation(getLoginMutationOptions(options));
};
export const getGetDemoAccountsUrl = () => {
    return `/api/auth/demo`;
};
/**
 * @summary List safe demo account labels
 */
export const getDemoAccounts = async (options) => {
    return customFetch(getGetDemoAccountsUrl(), {
        ...options,
        method: 'GET'
    });
};
export const getGetDemoAccountsQueryKey = () => {
    return [
        `/api/auth/demo`
    ];
};
export const getGetDemoAccountsQueryOptions = (options) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};
    const queryKey = queryOptions?.queryKey ?? getGetDemoAccountsQueryKey();
    const queryFn = ({ signal }) => getDemoAccounts({ signal, ...requestOptions });
    return { queryKey, queryFn, ...queryOptions };
};
/**
 * @summary List safe demo account labels
 */
export function useGetDemoAccounts(options) {
    const queryOptions = getGetDemoAccountsQueryOptions(options);
    const query = useQuery(queryOptions);
    return withQueryKey(query, queryOptions.queryKey);
}
export const getGetCurrentUserUrl = () => {
    return `/api/auth/me`;
};
/**
 * @summary Get the current session user
 */
export const getCurrentUser = async (options) => {
    return customFetch(getGetCurrentUserUrl(), {
        ...options,
        method: 'GET'
    });
};
export const getGetCurrentUserQueryKey = () => {
    return [
        `/api/auth/me`
    ];
};
export const getGetCurrentUserQueryOptions = (options) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};
    const queryKey = queryOptions?.queryKey ?? getGetCurrentUserQueryKey();
    const queryFn = ({ signal }) => getCurrentUser({ signal, ...requestOptions });
    return { queryKey, queryFn, ...queryOptions };
};
/**
 * @summary Get the current session user
 */
export function useGetCurrentUser(options) {
    const queryOptions = getGetCurrentUserQueryOptions(options);
    const query = useQuery(queryOptions);
    return withQueryKey(query, queryOptions.queryKey);
}
export const getLogoutUrl = () => {
    return `/api/auth/logout`;
};
/**
 * @summary End the current session
 */
export const logout = async (options) => {
    return customFetch(getLogoutUrl(), {
        ...options,
        method: 'POST'
    });
};
export const getLogoutMutationKey = () => ['logout'];
export const getLogoutMutationOptions = (options) => {
    const mutationKey = getLogoutMutationKey();
    const { mutation: mutationOptions, request: requestOptions } = options ?
        options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
            options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey, }, request: undefined };
    const mutationFn = () => {
        return logout(requestOptions);
    };
    return { mutationFn, ...mutationOptions };
};
/**
* @summary End the current session
*/
export const useLogout = (options) => {
    return useMutation(getLogoutMutationOptions(options));
};
export const getListStatesUrl = () => {
    return `/api/administration/states`;
};
/**
 * @summary List Indian states and union territories
 */
export const listStates = async (options) => {
    return customFetch(getListStatesUrl(), {
        ...options,
        method: 'GET'
    });
};
export const getListStatesQueryKey = () => {
    return [
        `/api/administration/states`
    ];
};
export const getListStatesQueryOptions = (options) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};
    const queryKey = queryOptions?.queryKey ?? getListStatesQueryKey();
    const queryFn = ({ signal }) => listStates({ signal, ...requestOptions });
    return { queryKey, queryFn, ...queryOptions };
};
/**
 * @summary List Indian states and union territories
 */
export function useListStates(options) {
    const queryOptions = getListStatesQueryOptions(options);
    const query = useQuery(queryOptions);
    return withQueryKey(query, queryOptions.queryKey);
}
export const getListDistrictsUrl = (stateCode) => {
    return `/api/administration/states/${stateCode}/districts`;
};
/**
 * @summary List districts for a state
 */
export const listDistricts = async (stateCode, options) => {
    return customFetch(getListDistrictsUrl(stateCode), {
        ...options,
        method: 'GET'
    });
};
export const getListDistrictsQueryKey = (stateCode) => {
    return [
        `/api/administration/states/${stateCode}/districts`
    ];
};
export const getListDistrictsQueryOptions = (stateCode, options) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};
    const queryKey = queryOptions?.queryKey ?? getListDistrictsQueryKey(stateCode);
    const queryFn = ({ signal }) => listDistricts(stateCode, { signal, ...requestOptions });
    return { queryKey, queryFn, enabled: stateCode !== null && stateCode !== undefined, ...queryOptions };
};
/**
 * @summary List districts for a state
 */
export function useListDistricts(stateCode, options) {
    const queryOptions = getListDistrictsQueryOptions(stateCode, options);
    const query = useQuery(queryOptions);
    return withQueryKey(query, queryOptions.queryKey);
}
export const getListConstituenciesUrl = (stateCode) => {
    return `/api/administration/states/${stateCode}/constituencies`;
};
/**
 * @summary List parliamentary constituencies for a state
 */
export const listConstituencies = async (stateCode, options) => {
    return customFetch(getListConstituenciesUrl(stateCode), {
        ...options,
        method: 'GET'
    });
};
export const getListConstituenciesQueryKey = (stateCode) => {
    return [
        `/api/administration/states/${stateCode}/constituencies`
    ];
};
export const getListConstituenciesQueryOptions = (stateCode, options) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};
    const queryKey = queryOptions?.queryKey ?? getListConstituenciesQueryKey(stateCode);
    const queryFn = ({ signal }) => listConstituencies(stateCode, { signal, ...requestOptions });
    return { queryKey, queryFn, enabled: stateCode !== null && stateCode !== undefined, ...queryOptions };
};
/**
 * @summary List parliamentary constituencies for a state
 */
export function useListConstituencies(stateCode, options) {
    const queryOptions = getListConstituenciesQueryOptions(stateCode, options);
    const query = useQuery(queryOptions);
    return withQueryKey(query, queryOptions.queryKey);
}
export const getGetDashboardSummaryUrl = () => {
    return `/api/dashboard/summary`;
};
/**
 * @summary Get scoped dashboard analytics
 */
export const getDashboardSummary = async (options) => {
    return customFetch(getGetDashboardSummaryUrl(), {
        ...options,
        method: 'GET'
    });
};
export const getGetDashboardSummaryQueryKey = () => {
    return [
        `/api/dashboard/summary`
    ];
};
export const getGetDashboardSummaryQueryOptions = (options) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};
    const queryKey = queryOptions?.queryKey ?? getGetDashboardSummaryQueryKey();
    const queryFn = ({ signal }) => getDashboardSummary({ signal, ...requestOptions });
    return { queryKey, queryFn, ...queryOptions };
};
/**
 * @summary Get scoped dashboard analytics
 */
export function useGetDashboardSummary(options) {
    const queryOptions = getGetDashboardSummaryQueryOptions(options);
    const query = useQuery(queryOptions);
    return withQueryKey(query, queryOptions.queryKey);
}
export const getListProjectsUrl = (params) => {
    const normalizedParams = new URLSearchParams();
    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? 'null' : String(value));
        }
    });
    const stringifiedParams = normalizedParams.toString();
    return stringifiedParams.length > 0 ? `/api/projects?${stringifiedParams}` : `/api/projects`;
};
/**
 * @summary List projects within the signed-in authority scope
 */
export const listProjects = async (params, options) => {
    return customFetch(getListProjectsUrl(params), {
        ...options,
        method: 'GET'
    });
};
export const getListProjectsQueryKey = (params) => {
    return [
        `/api/projects`, ...(params ? [params] : [])
    ];
};
export const getListProjectsQueryOptions = (params, options) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};
    const queryKey = queryOptions?.queryKey ?? getListProjectsQueryKey(params);
    const queryFn = ({ signal }) => listProjects(params, { signal, ...requestOptions });
    return { queryKey, queryFn, ...queryOptions };
};
/**
 * @summary List projects within the signed-in authority scope
 */
export function useListProjects(params, options) {
    const queryOptions = getListProjectsQueryOptions(params, options);
    const query = useQuery(queryOptions);
    return withQueryKey(query, queryOptions.queryKey);
}
export const getListEscalatedProjectsUrl = () => {
    return `/api/projects/escalated`;
};
/**
 * @summary List escalated projects pending review in user jurisdiction
 */
export const listEscalatedProjects = async (options) => {
    return customFetch(getListEscalatedProjectsUrl(), {
        ...options,
        method: 'GET'
    });
};
export const getListEscalatedProjectsQueryKey = () => {
    return [
        `/api/projects/escalated`
    ];
};
export const getListEscalatedProjectsQueryOptions = (options) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};
    const queryKey = queryOptions?.queryKey ?? getListEscalatedProjectsQueryKey();
    const queryFn = ({ signal }) => listEscalatedProjects({ signal, ...requestOptions });
    return { queryKey, queryFn, ...queryOptions };
};
/**
 * @summary List escalated projects pending review in user jurisdiction
 */
export function useListEscalatedProjects(options) {
    const queryOptions = getListEscalatedProjectsQueryOptions(options);
    const query = useQuery(queryOptions);
    return withQueryKey(query, queryOptions.queryKey);
}
export const getGetProjectUrl = (workId) => {
    return `/api/projects/${workId}`;
};
/**
 * @summary Get a project with findings and evidence
 */
export const getProject = async (workId, options) => {
    return customFetch(getGetProjectUrl(workId), {
        ...options,
        method: 'GET'
    });
};
export const getGetProjectQueryKey = (workId) => {
    return [
        `/api/projects/${workId}`
    ];
};
export const getGetProjectQueryOptions = (workId, options) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};
    const queryKey = queryOptions?.queryKey ?? getGetProjectQueryKey(workId);
    const queryFn = ({ signal }) => getProject(workId, { signal, ...requestOptions });
    return { queryKey, queryFn, enabled: workId !== null && workId !== undefined, ...queryOptions };
};
/**
 * @summary Get a project with findings and evidence
 */
export function useGetProject(workId, options) {
    const queryOptions = getGetProjectQueryOptions(workId, options);
    const query = useQuery(queryOptions);
    return withQueryKey(query, queryOptions.queryKey);
}
export const getCreateProjectActionUrl = (workId) => {
    return `/api/projects/${workId}/actions`;
};
/**
 * @summary Apply an authorized workflow action
 */
export const createProjectAction = async (workId, projectActionInput, options) => {
    const getHeaders = (h) => {
        if (!h)
            return {};
        if (h instanceof Headers)
            return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(Array.from(h, (entry) => Array.from(entry)));
        }
        const headers = {};
        for (const [name, value] of Object.entries(h)) {
            if (value !== undefined)
                headers[name] = value;
        }
        return headers;
    };
    return customFetch(getCreateProjectActionUrl(workId), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
        body: JSON.stringify(projectActionInput)
    });
};
export const getCreateProjectActionMutationKey = () => ['createProjectAction'];
export const getCreateProjectActionMutationOptions = (options) => {
    const mutationKey = getCreateProjectActionMutationKey();
    const { mutation: mutationOptions, request: requestOptions } = options ?
        options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
            options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey, }, request: undefined };
    const mutationFn = (props) => {
        const { workId, data } = props ?? {};
        return createProjectAction(workId, data, requestOptions);
    };
    return { mutationFn, ...mutationOptions };
};
/**
* @summary Apply an authorized workflow action
*/
export const useCreateProjectAction = (options) => {
    return useMutation(getCreateProjectActionMutationOptions(options));
};
export const getListProjectAuditUrl = (workId) => {
    return `/api/projects/${workId}/audit`;
};
/**
 * @summary Get project audit history
 */
export const listProjectAudit = async (workId, options) => {
    return customFetch(getListProjectAuditUrl(workId), {
        ...options,
        method: 'GET'
    });
};
export const getListProjectAuditQueryKey = (workId) => {
    return [
        `/api/projects/${workId}/audit`
    ];
};
export const getListProjectAuditQueryOptions = (workId, options) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};
    const queryKey = queryOptions?.queryKey ?? getListProjectAuditQueryKey(workId);
    const queryFn = ({ signal }) => listProjectAudit(workId, { signal, ...requestOptions });
    return { queryKey, queryFn, enabled: workId !== null && workId !== undefined, ...queryOptions };
};
/**
 * @summary Get project audit history
 */
export function useListProjectAudit(workId, options) {
    const queryOptions = getListProjectAuditQueryOptions(workId, options);
    const query = useQuery(queryOptions);
    return withQueryKey(query, queryOptions.queryKey);
}
export const getListRecentAuditUrl = () => {
    return `/api/audit/recent`;
};
/**
 * @summary Get recent scoped audit activity
 */
export const listRecentAudit = async (options) => {
    return customFetch(getListRecentAuditUrl(), {
        ...options,
        method: 'GET'
    });
};
export const getListRecentAuditQueryKey = () => {
    return [
        `/api/audit/recent`
    ];
};
export const getListRecentAuditQueryOptions = (options) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};
    const queryKey = queryOptions?.queryKey ?? getListRecentAuditQueryKey();
    const queryFn = ({ signal }) => listRecentAudit({ signal, ...requestOptions });
    return { queryKey, queryFn, ...queryOptions };
};
/**
 * @summary Get recent scoped audit activity
 */
export function useListRecentAudit(options) {
    const queryOptions = getListRecentAuditQueryOptions(options);
    const query = useQuery(queryOptions);
    return withQueryKey(query, queryOptions.queryKey);
}


export * from './schemas';
export * from './custom-fetch';
